/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedUniformRouteImport } from './routes/_authenticated/uniform'
import { Route as AuthenticatedTransportRouteImport } from './routes/_authenticated/transport'
import { Route as AuthenticatedTimetableRouteImport } from './routes/_authenticated/timetable'
import { Route as AuthenticatedSubjectsRouteImport } from './routes/_authenticated/subjects'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReportCardsRouteImport } from './routes/_authenticated/report-cards'
import { Route as AuthenticatedPupilsRouteImport } from './routes/_authenticated/pupils'
import { Route as AuthenticatedPromotionsRouteImport } from './routes/_authenticated/promotions'
import { Route as AuthenticatedProcurementRouteImport } from './routes/_authenticated/procurement'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedMarksRouteImport } from './routes/_authenticated/marks'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedLeaveRouteImport } from './routes/_authenticated/leave'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedInquiriesRouteImport } from './routes/_authenticated/inquiries'
import { Route as AuthenticatedHomeworkRouteImport } from './routes/_authenticated/homework'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedGuardiansRouteImport } from './routes/_authenticated/guardians'
import { Route as AuthenticatedFeesRouteImport } from './routes/_authenticated/fees'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDisciplineRouteImport } from './routes/_authenticated/discipline'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunicationRouteImport } from './routes/_authenticated/communication'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedCanteenRouteImport } from './routes/_authenticated/canteen'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBackupRouteImport } from './routes/_authenticated/backup'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAdmissionsRouteImport } from './routes/_authenticated/admissions'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedAcademicYearsRouteImport } from './routes/_authenticated/academic-years'
import { Route as AuthenticatedStaffStaffIdRouteImport } from './routes/_authenticated/staff_.$staffId'
import { Route as AuthenticatedPupilsPupilIdRouteImport } from './routes/_authenticated/pupils_.$pupilId'
import { Route as AuthenticatedGuardiansGuardianIdRouteImport } from './routes/_authenticated/guardians_.$guardianId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUniformRoute = AuthenticatedUniformRouteImport.update({
  id: '/uniform',
  path: '/uniform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransportRoute = AuthenticatedTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimetableRoute = AuthenticatedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubjectsRoute = AuthenticatedSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportCardsRoute =
  AuthenticatedReportCardsRouteImport.update({
    id: '/report-cards',
    path: '/report-cards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPupilsRoute = AuthenticatedPupilsRouteImport.update({
  id: '/pupils',
  path: '/pupils',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromotionsRoute = AuthenticatedPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcurementRoute =
  AuthenticatedProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarksRoute = AuthenticatedMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaveRoute = AuthenticatedLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInquiriesRoute = AuthenticatedInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeworkRoute = AuthenticatedHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuardiansRoute = AuthenticatedGuardiansRouteImport.update({
  id: '/guardians',
  path: '/guardians',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeesRoute = AuthenticatedFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisciplineRoute = AuthenticatedDisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunicationRoute =
  AuthenticatedCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCanteenRoute = AuthenticatedCanteenRouteImport.update({
  id: '/canteen',
  path: '/canteen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupRoute = AuthenticatedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdmissionsRoute = AuthenticatedAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcademicYearsRoute =
  AuthenticatedAcademicYearsRouteImport.update({
    id: '/academic-years',
    path: '/academic-years',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffStaffIdRoute =
  AuthenticatedStaffStaffIdRouteImport.update({
    id: '/staff_/$staffId',
    path: '/staff/$staffId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPupilsPupilIdRoute =
  AuthenticatedPupilsPupilIdRouteImport.update({
    id: '/pupils_/$pupilId',
    path: '/pupils/$pupilId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuardiansGuardianIdRoute =
  AuthenticatedGuardiansGuardianIdRouteImport.update({
    id: '/guardians_/$guardianId',
    path: '/guardians/$guardianId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/academic-years': typeof AuthenticatedAcademicYearsRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/canteen': typeof AuthenticatedCanteenRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discipline': typeof AuthenticatedDisciplineRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/guardians': typeof AuthenticatedGuardiansRoute
  '/health': typeof AuthenticatedHealthRoute
  '/homework': typeof AuthenticatedHomeworkRoute
  '/inquiries': typeof AuthenticatedInquiriesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/marks': typeof AuthenticatedMarksRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/pupils': typeof AuthenticatedPupilsRoute
  '/report-cards': typeof AuthenticatedReportCardsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/subjects': typeof AuthenticatedSubjectsRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/transport': typeof AuthenticatedTransportRoute
  '/uniform': typeof AuthenticatedUniformRoute
  '/users': typeof AuthenticatedUsersRoute
  '/guardians/$guardianId': typeof AuthenticatedGuardiansGuardianIdRoute
  '/pupils/$pupilId': typeof AuthenticatedPupilsPupilIdRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/academic-years': typeof AuthenticatedAcademicYearsRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/canteen': typeof AuthenticatedCanteenRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discipline': typeof AuthenticatedDisciplineRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/guardians': typeof AuthenticatedGuardiansRoute
  '/health': typeof AuthenticatedHealthRoute
  '/homework': typeof AuthenticatedHomeworkRoute
  '/inquiries': typeof AuthenticatedInquiriesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/marks': typeof AuthenticatedMarksRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/pupils': typeof AuthenticatedPupilsRoute
  '/report-cards': typeof AuthenticatedReportCardsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/subjects': typeof AuthenticatedSubjectsRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/transport': typeof AuthenticatedTransportRoute
  '/uniform': typeof AuthenticatedUniformRoute
  '/users': typeof AuthenticatedUsersRoute
  '/guardians/$guardianId': typeof AuthenticatedGuardiansGuardianIdRoute
  '/pupils/$pupilId': typeof AuthenticatedPupilsPupilIdRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/academic-years': typeof AuthenticatedAcademicYearsRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/admissions': typeof AuthenticatedAdmissionsRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/backup': typeof AuthenticatedBackupRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/canteen': typeof AuthenticatedCanteenRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/communication': typeof AuthenticatedCommunicationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discipline': typeof AuthenticatedDisciplineRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRoute
  '/_authenticated/fees': typeof AuthenticatedFeesRoute
  '/_authenticated/guardians': typeof AuthenticatedGuardiansRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/homework': typeof AuthenticatedHomeworkRoute
  '/_authenticated/inquiries': typeof AuthenticatedInquiriesRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/leave': typeof AuthenticatedLeaveRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/marks': typeof AuthenticatedMarksRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/procurement': typeof AuthenticatedProcurementRoute
  '/_authenticated/promotions': typeof AuthenticatedPromotionsRoute
  '/_authenticated/pupils': typeof AuthenticatedPupilsRoute
  '/_authenticated/report-cards': typeof AuthenticatedReportCardsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/subjects': typeof AuthenticatedSubjectsRoute
  '/_authenticated/timetable': typeof AuthenticatedTimetableRoute
  '/_authenticated/transport': typeof AuthenticatedTransportRoute
  '/_authenticated/uniform': typeof AuthenticatedUniformRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/guardians_/$guardianId': typeof AuthenticatedGuardiansGuardianIdRoute
  '/_authenticated/pupils_/$pupilId': typeof AuthenticatedPupilsPupilIdRoute
  '/_authenticated/staff_/$staffId': typeof AuthenticatedStaffStaffIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/change-password'
    | '/forgot-password'
    | '/reset-password'
    | '/academic-years'
    | '/accounts'
    | '/admissions'
    | '/announcements'
    | '/attendance'
    | '/audit'
    | '/backup'
    | '/calendar'
    | '/canteen'
    | '/classes'
    | '/communication'
    | '/dashboard'
    | '/discipline'
    | '/documents'
    | '/exams'
    | '/fees'
    | '/guardians'
    | '/health'
    | '/homework'
    | '/inquiries'
    | '/inventory'
    | '/leave'
    | '/library'
    | '/marks'
    | '/meetings'
    | '/payroll'
    | '/portal'
    | '/procurement'
    | '/promotions'
    | '/pupils'
    | '/report-cards'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/subjects'
    | '/timetable'
    | '/transport'
    | '/uniform'
    | '/users'
    | '/guardians/$guardianId'
    | '/pupils/$pupilId'
    | '/staff/$staffId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/forgot-password'
    | '/reset-password'
    | '/academic-years'
    | '/accounts'
    | '/admissions'
    | '/announcements'
    | '/attendance'
    | '/audit'
    | '/backup'
    | '/calendar'
    | '/canteen'
    | '/classes'
    | '/communication'
    | '/dashboard'
    | '/discipline'
    | '/documents'
    | '/exams'
    | '/fees'
    | '/guardians'
    | '/health'
    | '/homework'
    | '/inquiries'
    | '/inventory'
    | '/leave'
    | '/library'
    | '/marks'
    | '/meetings'
    | '/payroll'
    | '/portal'
    | '/procurement'
    | '/promotions'
    | '/pupils'
    | '/report-cards'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/subjects'
    | '/timetable'
    | '/transport'
    | '/uniform'
    | '/users'
    | '/guardians/$guardianId'
    | '/pupils/$pupilId'
    | '/staff/$staffId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/change-password'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/academic-years'
    | '/_authenticated/accounts'
    | '/_authenticated/admissions'
    | '/_authenticated/announcements'
    | '/_authenticated/attendance'
    | '/_authenticated/audit'
    | '/_authenticated/backup'
    | '/_authenticated/calendar'
    | '/_authenticated/canteen'
    | '/_authenticated/classes'
    | '/_authenticated/communication'
    | '/_authenticated/dashboard'
    | '/_authenticated/discipline'
    | '/_authenticated/documents'
    | '/_authenticated/exams'
    | '/_authenticated/fees'
    | '/_authenticated/guardians'
    | '/_authenticated/health'
    | '/_authenticated/homework'
    | '/_authenticated/inquiries'
    | '/_authenticated/inventory'
    | '/_authenticated/leave'
    | '/_authenticated/library'
    | '/_authenticated/marks'
    | '/_authenticated/meetings'
    | '/_authenticated/payroll'
    | '/_authenticated/portal'
    | '/_authenticated/procurement'
    | '/_authenticated/promotions'
    | '/_authenticated/pupils'
    | '/_authenticated/report-cards'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/subjects'
    | '/_authenticated/timetable'
    | '/_authenticated/transport'
    | '/_authenticated/uniform'
    | '/_authenticated/users'
    | '/_authenticated/guardians_/$guardianId'
    | '/_authenticated/pupils_/$pupilId'
    | '/_authenticated/staff_/$staffId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/uniform': {
      id: '/_authenticated/uniform'
      path: '/uniform'
      fullPath: '/uniform'
      preLoaderRoute: typeof AuthenticatedUniformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transport': {
      id: '/_authenticated/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof AuthenticatedTransportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable': {
      id: '/_authenticated/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects': {
      id: '/_authenticated/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthenticatedSubjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report-cards': {
      id: '/_authenticated/report-cards'
      path: '/report-cards'
      fullPath: '/report-cards'
      preLoaderRoute: typeof AuthenticatedReportCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pupils': {
      id: '/_authenticated/pupils'
      path: '/pupils'
      fullPath: '/pupils'
      preLoaderRoute: typeof AuthenticatedPupilsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promotions': {
      id: '/_authenticated/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement': {
      id: '/_authenticated/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AuthenticatedProcurementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marks': {
      id: '/_authenticated/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof AuthenticatedMarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave': {
      id: '/_authenticated/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedLeaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquiries': {
      id: '/_authenticated/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof AuthenticatedInquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/homework': {
      id: '/_authenticated/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof AuthenticatedHomeworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guardians': {
      id: '/_authenticated/guardians'
      path: '/guardians'
      fullPath: '/guardians'
      preLoaderRoute: typeof AuthenticatedGuardiansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees': {
      id: '/_authenticated/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AuthenticatedFeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discipline': {
      id: '/_authenticated/discipline'
      path: '/discipline'
      fullPath: '/discipline'
      preLoaderRoute: typeof AuthenticatedDisciplineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communication': {
      id: '/_authenticated/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof AuthenticatedCommunicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canteen': {
      id: '/_authenticated/canteen'
      path: '/canteen'
      fullPath: '/canteen'
      preLoaderRoute: typeof AuthenticatedCanteenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup': {
      id: '/_authenticated/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthenticatedBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admissions': {
      id: '/_authenticated/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AuthenticatedAdmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic-years': {
      id: '/_authenticated/academic-years'
      path: '/academic-years'
      fullPath: '/academic-years'
      preLoaderRoute: typeof AuthenticatedAcademicYearsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff_/$staffId': {
      id: '/_authenticated/staff_/$staffId'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pupils_/$pupilId': {
      id: '/_authenticated/pupils_/$pupilId'
      path: '/pupils/$pupilId'
      fullPath: '/pupils/$pupilId'
      preLoaderRoute: typeof AuthenticatedPupilsPupilIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guardians_/$guardianId': {
      id: '/_authenticated/guardians_/$guardianId'
      path: '/guardians/$guardianId'
      fullPath: '/guardians/$guardianId'
      preLoaderRoute: typeof AuthenticatedGuardiansGuardianIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcademicYearsRoute: typeof AuthenticatedAcademicYearsRoute
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAdmissionsRoute: typeof AuthenticatedAdmissionsRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBackupRoute: typeof AuthenticatedBackupRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCanteenRoute: typeof AuthenticatedCanteenRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedCommunicationRoute: typeof AuthenticatedCommunicationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisciplineRoute: typeof AuthenticatedDisciplineRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRoute
  AuthenticatedFeesRoute: typeof AuthenticatedFeesRoute
  AuthenticatedGuardiansRoute: typeof AuthenticatedGuardiansRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedHomeworkRoute: typeof AuthenticatedHomeworkRoute
  AuthenticatedInquiriesRoute: typeof AuthenticatedInquiriesRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLeaveRoute: typeof AuthenticatedLeaveRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMarksRoute: typeof AuthenticatedMarksRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedProcurementRoute: typeof AuthenticatedProcurementRoute
  AuthenticatedPromotionsRoute: typeof AuthenticatedPromotionsRoute
  AuthenticatedPupilsRoute: typeof AuthenticatedPupilsRoute
  AuthenticatedReportCardsRoute: typeof AuthenticatedReportCardsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedSubjectsRoute: typeof AuthenticatedSubjectsRoute
  AuthenticatedTimetableRoute: typeof AuthenticatedTimetableRoute
  AuthenticatedTransportRoute: typeof AuthenticatedTransportRoute
  AuthenticatedUniformRoute: typeof AuthenticatedUniformRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedGuardiansGuardianIdRoute: typeof AuthenticatedGuardiansGuardianIdRoute
  AuthenticatedPupilsPupilIdRoute: typeof AuthenticatedPupilsPupilIdRoute
  AuthenticatedStaffStaffIdRoute: typeof AuthenticatedStaffStaffIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcademicYearsRoute: AuthenticatedAcademicYearsRoute,
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAdmissionsRoute: AuthenticatedAdmissionsRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBackupRoute: AuthenticatedBackupRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCanteenRoute: AuthenticatedCanteenRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedCommunicationRoute: AuthenticatedCommunicationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisciplineRoute: AuthenticatedDisciplineRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRoute,
  AuthenticatedFeesRoute: AuthenticatedFeesRoute,
  AuthenticatedGuardiansRoute: AuthenticatedGuardiansRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedHomeworkRoute: AuthenticatedHomeworkRoute,
  AuthenticatedInquiriesRoute: AuthenticatedInquiriesRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLeaveRoute: AuthenticatedLeaveRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMarksRoute: AuthenticatedMarksRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedProcurementRoute: AuthenticatedProcurementRoute,
  AuthenticatedPromotionsRoute: AuthenticatedPromotionsRoute,
  AuthenticatedPupilsRoute: AuthenticatedPupilsRoute,
  AuthenticatedReportCardsRoute: AuthenticatedReportCardsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedSubjectsRoute: AuthenticatedSubjectsRoute,
  AuthenticatedTimetableRoute: AuthenticatedTimetableRoute,
  AuthenticatedTransportRoute: AuthenticatedTransportRoute,
  AuthenticatedUniformRoute: AuthenticatedUniformRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedGuardiansGuardianIdRoute: AuthenticatedGuardiansGuardianIdRoute,
  AuthenticatedPupilsPupilIdRoute: AuthenticatedPupilsPupilIdRoute,
  AuthenticatedStaffStaffIdRoute: AuthenticatedStaffStaffIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
